# Generated by Django 4.1.7 on 2023-03-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(max_length=128)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=models.SET('deleted'), to='menu.menu')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menu',
                'ordering': ['created_date'],
            },
        ),
    ]
