# Generated by Django 4.1.7 on 2023-03-23 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuperMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'verbose_name': 'Super menu',
                'verbose_name_plural': 'Super menu',
            },
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['count'], 'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
        migrations.AddField(
            model_name='menu',
            name='count',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='menu',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='menu_item', to='menu.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='super_parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='menu.supermenu'),
            preserve_default=False,
        ),
    ]
