# Generated by Django 4.1.7 on 2023-03-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_supermenu_alter_menu_options_menu_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supermenu',
            name='name',
            field=models.CharField(db_index=True, max_length=128),
        ),
    ]
