# Generated by Django 4.1.7 on 2023-03-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_supermenu_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['level'], 'verbose_name': 'menu', 'verbose_name_plural': 'menu'},
        ),
        migrations.RenameField(
            model_name='menu',
            old_name='count',
            new_name='level',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='changed_date',
        ),
        migrations.RemoveField(
            model_name='menu',
            name='created_date',
        ),
        migrations.AlterField(
            model_name='supermenu',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
